const techStack = {
  intro: "Technologies I work with include but are not limited to:",
  techs: [
    "JavaScript",
    "TypeScript",
    "Python",
    "Java",
    "C#",
    "C++",
    "C",
    "PHP",
    "Kotlin",
    "R",
    "Assembly",
    "PowerShell",
    "Bash",
    "SQL",
    "NoSQL",
    "Solidity",
    "React",
    "Next.js",
    "HTML",
    "CSS",
    "PostCSS",
    "Tailwind CSS",
    "Bootstrap",
    "Material-UI",
    "CSS Modules",
    "Webpack",
    "Vite",
    "esbuild",
    "Context API",
    "Node.js",
    "Express.js",
    "Spring Boot",
    "Spring Framework",
    "ASP.NET",
    "ASP.NET Core",
    ".NET Framework",
    ".NET Core",
    ".NET 5+",
    "Entity Framework",
    "Laravel",
    "PostgreSQL",
    "MySQL",
    "SQLite",
    "Oracle",
    "SQL Server",
    "MongoDB",
    "Redis",
    "Netlify",
    "Vercel",
    "Railway",
    "Render",
    "Supabase",
    "GitHub Actions",
    "Git",
    "GitHub",
    "Visual Studio Code",
    "IntelliJ IDEA",
    "Visual Studio",
    "npm",
    "yarn",
    "pnpm",
    "pip",
    "conda",
    "NuGet",
    "Postman",
    "OAuth",
    "JWT",
  ],
};

export default techStack; 